name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  check_server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js dependencies
      run: npm install 

    - name: Check if Server Starts
      run: node -e "console.log('Server starts successfully')"

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: check_server
    if: ${{ always() }} # Ensure this job runs regardless of the outcome of the previous job

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      if: ${{ needs.check_server.success }} # Only build and push image if the server started successfully
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/docker-sample:latest





    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKER_USERNAME }}/docker-sample:latest
    # tags: ${{ secrets.DOCKER_USERNAME }}/docker-sample:main-${{ github.run_number }}